/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'outline': '#747879',
        'surface-container-highest': '#e1e2e6',
        'primary-fixed': '#e1e3e4',
        'on-error-container': '#93000a',
        'outline-variant': '#c4c7c8',
        'on-primary-container': '#828586',
        'primary': '#010202',
        'primary-fixed-dim': '#c5c7c8',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e7e8eb',
        'surface-dim': '#d9dadd',
        'secondary-fixed-dim': '#e9c176',
        'tertiary-fixed-dim': '#c8c6c2',
        'on-secondary-fixed-variant': '#5d4201',
        'on-tertiary-container': '#858581',
        'background': '#f9f9fc',
        'secondary-container': '#fed488',
        'inverse-primary': '#c5c7c8',
        'inverse-on-surface': '#f0f0f4',
        'primary-container': '#1a1d1e',
        'surface-tint': '#5c5f60',
        'tertiary': '#020201',
        'surface-bright': '#f9f9fc',
        'on-background': '#191c1e',
        'inverse-surface': '#2e3133',
        'on-secondary-container': '#785a1a',
        'on-primary-fixed-variant': '#444748',
        'on-surface': '#191c1e',
        'surface-variant': '#e1e2e6',
        'surface-container-low': '#f3f3f7',
        'error': '#ba1a1a',
        'secondary': '#775a19',
        'surface-container': '#edeef1',
        'tertiary-container': '#1c1d1a',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#1b1c19',
        'on-surface-variant': '#444749',
        'on-primary-fixed': '#191c1d',
        'surface': '#f9f9fc',
        'on-secondary-fixed': '#261900',
        'secondary-fixed': '#ffdea5',
        'tertiary-fixed': '#e4e2dd',
        'on-tertiary-fixed-variant': '#474744',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '8px',
        'container-max': '1440px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        gutter: '24px',
        'sidebar-width': '280px',
      },
      fontFamily: {
        'label-md': ['Hanken Grotesk'],
        'label-sm': ['Hanken Grotesk'],
        'body-lg': ['Hanken Grotesk'],
        'title-lg': ['Hanken Grotesk'],
        'display-lg': ['Libre Caslon Text'],
        'headline-sm': ['Libre Caslon Text'],
        'body-md': ['Hanken Grotesk'],
        'display-lg-mobile': ['Libre Caslon Text'],
        'headline-md': ['Libre Caslon Text'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}